# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e97262a7452d51642d19c92fb0fccd3e48cb50bc7b3553cf6889b031b183b73387440fec8ad4d84b36a794b2d200115f203a661f0e85e3bb33a510b9910a25b

test:
  secret_key_base: 7aff9780ea7c1efc14269f843642bcf400adcd4cfe6c43c91b57b856ddfef43f398efd06730b975d86fb17dcaea735dd4e4a5a2641f2a45999341d24b8e83893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
